vim.api.nvim_set_hl(0, "HopNextKey", { fg = '#FF8F40' })
vim.api.nvim_set_hl(0, "HopNextKey1", { fg = '#59C2FF' })
vim.api.nvim_set_hl(0, "HopNextKey2", { fg = '#C2D94C' })
vim.api.nvim_set_hl(0, "BufferVisible", { link = "BufferInactive" })
vim.api.nvim_set_hl(0, "BufferVisibleIcon", { link = "BufferInactive" })
vim.api.nvim_set_hl(0, "BufferVisibleSign", { link = "BufferInactive" })
vim.api.nvim_set_hl(0, "BufferCurrentMod", { link = "GitGutterChange" })
vim.api.nvim_set_hl(0, "BufferVisibleMod", { link = "GitGutterChange" })
vim.api.nvim_set_hl(0, "BufferInactiveMod", { link = "GitGutterChange" })

vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { bg = "NONE", strikethrough = true, fg = "#808080" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { bg = "NONE", fg = "#569CD6" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { bg = "NONE", fg = "#569CD6" })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { bg = "NONE", fg = "#9CDCFE" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { bg = "NONE", fg = "#9CDCFE" })
vim.api.nvim_set_hl(0, "CmpItemKindText", { bg = "NONE", fg = "#9CDCFE" })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { bg = "NONE", fg = "#C586C0" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { bg = "NONE", fg = "#C586C0" })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { bg = "NONE", fg = "#D4D4D4" })
vim.api.nvim_set_hl(0, "CmpItemKindProperty", { bg = "NONE", fg = "#D4D4D4" })
vim.api.nvim_set_hl(0, "CmpItemKindUnit", { bg = "NONE", fg = "#D4D4D4" })

vim.api.nvim_set_hl(0, "OutlineIndent", { fg = "#FF8F40" })
vim.api.nvim_set_hl(0, "SagaShadow", { bg = "#000000" })
