return {
  'folke/snacks.nvim',
  opts = {
    notifier = {
      top_down = false,
      width = { min = 60, max = 60 },
      height = { min = 1, max = 8 },
      icons = {
        error = ' ',
        warn = ' ',
        info = ' ',
        debug = ' ',
        trace = ' ',
      },
    },
    dashboard = {
      width = 72,
      autokeys = 'abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      sections = {
        {
          section = 'terminal',
          align = 'center',
          cmd = 'cat | cat ' .. vim.fn.stdpath('config') .. '/lua/plugins/ui/header.cat',
          height = 11,
          width = 72,
          padding = 1,
        },
        {
          align = 'center',
          padding = 1,
          text = {
            { '  Update ', hl = 'Label' },
            { '  Sessions ', hl = '@property' },
            { '  Last Session ', hl = 'Number' },
            { '  Files ', hl = 'DiagnosticInfo' },
            { '  Recent ', hl = '@string' },
          },
        },
        { section = 'startup', padding = 1 },
        { icon = '󰏓 ', title = 'Projects', section = 'projects', indent = 2, padding = 1 },
        { icon = ' ', title = 'Recent Files', section = 'recent_files', indent = 2, padding = 1 },
        {
          section = 'terminal',
          icon = ' ',
          title = 'Git Status',
          enabled = vim.fn.isdirectory('.git') == 1,
          cmd = 'hub diff --stat -B -M -C',
          height = 8,
          padding = 0,
          indent = 2,
        },
        { text = '', action = ':Lazy update', key = 'u' },
        { text = '', action = ':PersistenceLoadSession', key = 's' },
        { text = '', action = ':PersistenceLoadLast', key = 'l' },
        { text = '', action = ':Telescope find_files', key = 'f' },
        { text = '', action = ':Telescope oldfiles', key = 'r' },
      },
    },
  },
}
