return {
  'onsails/lspkind.nvim',
  optional = true,
  opts = {
    mode = 'symbol',
    preset = 'codicons',
    symbol_map = {
      Class = '',
      Color = '',
      Constant = '',
      Constructor = '',
      Copilot = '',
      Enum = '',
      EnumMember = '',
      Event = '',
      Field = '',
      File = '',
      Folder = '',
      Function = '',
      Interface = '',
      Keyword = '',
      Method = '',
      Module = '',
      Operator = '',
      Property = '',
      Reference = '',
      Snippet = '',
      Struct = '',
      Text = '',
      TypeParameter = '',
      Unit = '',
      Value = '',
      Variable = '',
    },
  },
}
