return {
  {
    'folke/which-key.nvim',
    optional = true,
    opts = {
      spec = {
        { '<leader>lo', group = 'OpenCode', mode = { 'n', 'v' } },
        { '<leader>lc', group = 'Cursor', mode = { 'n', 'v' } },
        { '<leader>lg', group = 'Gemini', mode = { 'n', 'v' } },
        { '<leader>l', group = 'llm', mode = { 'n', 'v' } },
      },
    },
  },
  {
    dir = vim.fn.stdpath('config') .. '/local/agents',
    name = 'agents',
    event = { 'User LazyBufEnter' },
    opts = {
      cursor = {
        executable = 'agent',
        filetype = 'cursor-agent',
        display_name = 'Cursor',
        leader = '<leader>lc',
        split = 'right',
        focus = true,
        insert = false,
      },
      opencode = {
        executable = 'opencode',
        filetype = 'opencode',
        display_name = 'OpenCode',
        leader = '<leader>lo',
        split = 'right',
        focus = true,
        insert = false,
      },
      opencode2 = {
        executable = 'opencode2',
        filetype = 'opencode2',
        display_name = 'OpenCode2',
        leader = '<leader>l2',
        split = 'right',
        focus = true,
        insert = false,
      },
      gemini = {
        executable = 'agy',
        filetype = 'gemini',
        display_name = 'Gemini',
        leader = '<leader>lg',
        split = 'right',
        focus = true,
        insert = false,
      },
      claude = {
        executable = 'claude',
        filetype = 'claude',
        display_name = 'Claude',
        leader = '<leader>lu',
        split = 'right',
        focus = true,
        insert = false,
      },
      codex = {
        executable = 'codex',
        filetype = 'codex',
        display_name = 'Codex',
        leader = '<leader>lx',
        split = 'right',
        focus = true,
        insert = false,
      },
    },
  },
}
