return {
  ['null-ls'] = '',
  ['rust-analyzer'] = '󱘗',
  ansiblels = '󱂚',
  basedpyright = '󱔎',
  clangd = '',
  copilot = '',
  docker_compose_language_service = '',
  dockerls = '󰡨',
  gitlab_ci_ls = '',
  gopls = '',
  jsonls = '',
  lua_ls = '󰢱',
  marksman = '',
  neocmake = '',
  nil_ls = '',
  pylsp = '󰌠',
  ruff= '󰌠',
  ruff_lsp = '󱔎',
  taplo = '',
  tsserver = '󰛦',
  typos_lsp = '',
  vtsls = '',
  yamlls = '',
}
