-- stylua: ignore
return {
  ['GitHub Copilot']              = '',
  ['cspell_lsp']                  = '',
  ['null-ls']                     = '',
  ['obsidian-ls']                 = '',
  ['rust-analyzer']               = '󱘗',
  ansiblels                       = '󱂚',
  basedpyright                    = '󱔎',
  bashls                          = '',
  clangd                          = '',
  copilot                         = '',
  codebook                        = '',
  docker_compose_language_service = '',
  dockerls                        = '󰡨',
  gitlab_ci_ls                    = '',
  gitlab_code_suggestions         = '󰮠',
  gopls                           = '',
  hyprls                          = '',
  jsonls                          = '',
  stylua                          = '',
  lua_ls                          = '󰢱',
  marksman                        = '',
  neocmake                        = '',
  nil_ls                          = '',
  pylsp                           = '󰌠',
  qmlls                           = '',
  ruff                            = '󰌠',
  ruff_lsp                        = '󱔎',
  taplo                           = '',
  tsserver                        = '󰛦',
  typos_lsp                       = '',
  vtsls                           = '',
  yamlls                          = '',
}
