return {
  dir = vim.fn.stdpath('config') .. '/local/winpick',
  name = 'winpick',
  keys = {
    { '<leader>k', function() require('winpick').pick() end, desc = 'Jump To Window' },
  },
  ---@type Winpick.Config
  opts = {
    highlight = 'FloatTitle',
    border = {' '},
    chars = {
      'a',
      's',
      'd',
      'f',
      'g',
      'h',
      'j',
      'k',
      'l',
      ';',
      'q',
      'w',
      'e',
      'r',
      't',
      'y',
      'u',
      'i',
      'o',
      'p',
      'z',
      'x',
      'c',
      'v',
      'b',
      'n',
      'm',
      ',',
    },
  },
}
